version: "3.2"

services:
  api:
    image: node:alpine
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: npm start
